//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Players
{
    public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""PlayerMain"",
            ""id"": ""d2239dd4-b303-40d6-9433-310177f0543a"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""5dae9d0c-371f-4b6c-b969-02f5a0aac98a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""9b0ee411-d3d6-4eac-b43f-ba381a4ebeb6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FastUsing0"",
                    ""type"": ""Button"",
                    ""id"": ""7ec35eb9-158c-47a5-8ea0-4813c9c36a83"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastUsing1"",
                    ""type"": ""Button"",
                    ""id"": ""d4f73ef6-c53b-4574-9199-97396feffe99"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastUsing2"",
                    ""type"": ""Button"",
                    ""id"": ""6aec4d86-10c8-43c5-9017-d87b15808f68"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastUsing3"",
                    ""type"": ""Button"",
                    ""id"": ""e6298ae5-8186-4c84-a4f8-4a979882de66"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastUsing4"",
                    ""type"": ""Button"",
                    ""id"": ""a2e94c35-e01f-4f7e-9f2d-cfd2090ec5e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastUsing5"",
                    ""type"": ""Button"",
                    ""id"": ""e9152b7e-d11b-425e-bb31-e2c237b97568"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastUsing6"",
                    ""type"": ""Button"",
                    ""id"": ""4f403136-4b3c-4389-bbc5-e7bb60db4b2e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastUsing7"",
                    ""type"": ""Button"",
                    ""id"": ""1e675745-c576-4eb9-9c42-84591c7d0ee0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastUsing8"",
                    ""type"": ""Button"",
                    ""id"": ""c480d386-1227-4d4f-aa4c-08c3364dc62a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastUsing9"",
                    ""type"": ""Button"",
                    ""id"": ""94bb3485-b04c-4669-b97c-7f8c6bafcd0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CraftWindows"",
                    ""type"": ""Button"",
                    ""id"": ""b7112380-aadd-4076-bce2-caf7d4fea83a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryWindows"",
                    ""type"": ""Button"",
                    ""id"": ""5c65c049-2dfd-4a86-ad3f-7e0135bfcbea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c23c5754-4c95-47da-b544-f0b49593e1e8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""37f01c9c-3f93-4171-9b82-1841c32bf2ee"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3adae854-72b1-4394-afd1-49ca9f237da2"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a52b4251-b820-4206-a8c8-27bf703d6f24"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8dd328fc-2d7f-45be-97b4-43c9a6f25e64"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d37c9387-aef5-4183-83dc-06727ba2c46c"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6bb0a02f-d3b3-4ac9-8f85-ca40439d454d"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastUsing0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ec3074e-ac60-4480-83b7-bcf4e28fc6b2"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CraftWindows"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa100f6d-21db-466b-ba53-c52c75e3e89e"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastUsing1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8fa60ca9-a01c-4551-805e-007cb1e0fba1"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastUsing2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2dbc12ef-15b1-4335-b2d2-fbe2da8ebb5b"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastUsing3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a07b65a8-b1e4-4d04-b76f-f7c8a0a509c3"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastUsing4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e11e8b4-79f5-45fa-8968-2835474edcc6"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastUsing5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2662f796-e434-4c7b-b078-7d11403e6acd"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastUsing6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""201b1855-8d52-498d-a655-993b2e0a9ad8"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastUsing7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c1f15a1-4bcf-4365-96f4-6d2cadca46a4"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastUsing8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78604e87-573f-432c-bf72-6b0a78472c09"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastUsing9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68fa88d8-ba75-47a6-86e5-7bdecc50492b"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryWindows"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerUse"",
            ""id"": ""572c3e28-73d6-41a3-93e3-c56f365b9ae6"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""36636405-254e-40ee-84f1-aec6488ebc2a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""060669eb-7848-4024-949c-728466b28504"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""6d5417f9-aec2-447b-8406-5f16848f83b3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8d6a0792-3d7d-4f95-a822-2443c830d25f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b2daaba6-cee0-4b35-b02e-8d92de49b3e7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a99f4811-06bc-4d05-b203-66e577466e69"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d6753a62-0d15-4c27-9987-61f68ecb8a98"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e31c5a9c-aded-401e-aff1-ef0551a57549"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Window"",
            ""id"": ""d9445b8c-27fb-4b14-96be-3061fe25edbd"",
            ""actions"": [
                {
                    ""name"": ""CloseWindows"",
                    ""type"": ""Button"",
                    ""id"": ""61944149-2407-47e6-aadd-a2d0854e2814"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""09b64950-549d-4ed6-ab88-db4d0a02399a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseWindows"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // PlayerMain
            m_PlayerMain = asset.FindActionMap("PlayerMain", throwIfNotFound: true);
            m_PlayerMain_Movement = m_PlayerMain.FindAction("Movement", throwIfNotFound: true);
            m_PlayerMain_Look = m_PlayerMain.FindAction("Look", throwIfNotFound: true);
            m_PlayerMain_FastUsing0 = m_PlayerMain.FindAction("FastUsing0", throwIfNotFound: true);
            m_PlayerMain_FastUsing1 = m_PlayerMain.FindAction("FastUsing1", throwIfNotFound: true);
            m_PlayerMain_FastUsing2 = m_PlayerMain.FindAction("FastUsing2", throwIfNotFound: true);
            m_PlayerMain_FastUsing3 = m_PlayerMain.FindAction("FastUsing3", throwIfNotFound: true);
            m_PlayerMain_FastUsing4 = m_PlayerMain.FindAction("FastUsing4", throwIfNotFound: true);
            m_PlayerMain_FastUsing5 = m_PlayerMain.FindAction("FastUsing5", throwIfNotFound: true);
            m_PlayerMain_FastUsing6 = m_PlayerMain.FindAction("FastUsing6", throwIfNotFound: true);
            m_PlayerMain_FastUsing7 = m_PlayerMain.FindAction("FastUsing7", throwIfNotFound: true);
            m_PlayerMain_FastUsing8 = m_PlayerMain.FindAction("FastUsing8", throwIfNotFound: true);
            m_PlayerMain_FastUsing9 = m_PlayerMain.FindAction("FastUsing9", throwIfNotFound: true);
            m_PlayerMain_CraftWindows = m_PlayerMain.FindAction("CraftWindows", throwIfNotFound: true);
            m_PlayerMain_InventoryWindows = m_PlayerMain.FindAction("InventoryWindows", throwIfNotFound: true);
            // PlayerUse
            m_PlayerUse = asset.FindActionMap("PlayerUse", throwIfNotFound: true);
            m_PlayerUse_Movement = m_PlayerUse.FindAction("Movement", throwIfNotFound: true);
            m_PlayerUse_Look = m_PlayerUse.FindAction("Look", throwIfNotFound: true);
            // Window
            m_Window = asset.FindActionMap("Window", throwIfNotFound: true);
            m_Window_CloseWindows = m_Window.FindAction("CloseWindows", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // PlayerMain
        private readonly InputActionMap m_PlayerMain;
        private IPlayerMainActions m_PlayerMainActionsCallbackInterface;
        private readonly InputAction m_PlayerMain_Movement;
        private readonly InputAction m_PlayerMain_Look;
        private readonly InputAction m_PlayerMain_FastUsing0;
        private readonly InputAction m_PlayerMain_FastUsing1;
        private readonly InputAction m_PlayerMain_FastUsing2;
        private readonly InputAction m_PlayerMain_FastUsing3;
        private readonly InputAction m_PlayerMain_FastUsing4;
        private readonly InputAction m_PlayerMain_FastUsing5;
        private readonly InputAction m_PlayerMain_FastUsing6;
        private readonly InputAction m_PlayerMain_FastUsing7;
        private readonly InputAction m_PlayerMain_FastUsing8;
        private readonly InputAction m_PlayerMain_FastUsing9;
        private readonly InputAction m_PlayerMain_CraftWindows;
        private readonly InputAction m_PlayerMain_InventoryWindows;
        public struct PlayerMainActions
        {
            private @PlayerInputActions m_Wrapper;
            public PlayerMainActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Movement => m_Wrapper.m_PlayerMain_Movement;
            public InputAction @Look => m_Wrapper.m_PlayerMain_Look;
            public InputAction @FastUsing0 => m_Wrapper.m_PlayerMain_FastUsing0;
            public InputAction @FastUsing1 => m_Wrapper.m_PlayerMain_FastUsing1;
            public InputAction @FastUsing2 => m_Wrapper.m_PlayerMain_FastUsing2;
            public InputAction @FastUsing3 => m_Wrapper.m_PlayerMain_FastUsing3;
            public InputAction @FastUsing4 => m_Wrapper.m_PlayerMain_FastUsing4;
            public InputAction @FastUsing5 => m_Wrapper.m_PlayerMain_FastUsing5;
            public InputAction @FastUsing6 => m_Wrapper.m_PlayerMain_FastUsing6;
            public InputAction @FastUsing7 => m_Wrapper.m_PlayerMain_FastUsing7;
            public InputAction @FastUsing8 => m_Wrapper.m_PlayerMain_FastUsing8;
            public InputAction @FastUsing9 => m_Wrapper.m_PlayerMain_FastUsing9;
            public InputAction @CraftWindows => m_Wrapper.m_PlayerMain_CraftWindows;
            public InputAction @InventoryWindows => m_Wrapper.m_PlayerMain_InventoryWindows;
            public InputActionMap Get() { return m_Wrapper.m_PlayerMain; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerMainActions set) { return set.Get(); }
            public void SetCallbacks(IPlayerMainActions instance)
            {
                if (m_Wrapper.m_PlayerMainActionsCallbackInterface != null)
                {
                    @Movement.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnMovement;
                    @Movement.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnMovement;
                    @Movement.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnMovement;
                    @Look.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnLook;
                    @Look.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnLook;
                    @Look.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnLook;
                    @FastUsing0.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing0;
                    @FastUsing0.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing0;
                    @FastUsing0.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing0;
                    @FastUsing1.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing1;
                    @FastUsing1.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing1;
                    @FastUsing1.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing1;
                    @FastUsing2.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing2;
                    @FastUsing2.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing2;
                    @FastUsing2.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing2;
                    @FastUsing3.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing3;
                    @FastUsing3.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing3;
                    @FastUsing3.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing3;
                    @FastUsing4.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing4;
                    @FastUsing4.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing4;
                    @FastUsing4.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing4;
                    @FastUsing5.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing5;
                    @FastUsing5.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing5;
                    @FastUsing5.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing5;
                    @FastUsing6.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing6;
                    @FastUsing6.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing6;
                    @FastUsing6.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing6;
                    @FastUsing7.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing7;
                    @FastUsing7.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing7;
                    @FastUsing7.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing7;
                    @FastUsing8.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing8;
                    @FastUsing8.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing8;
                    @FastUsing8.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing8;
                    @FastUsing9.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing9;
                    @FastUsing9.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing9;
                    @FastUsing9.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnFastUsing9;
                    @CraftWindows.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnCraftWindows;
                    @CraftWindows.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnCraftWindows;
                    @CraftWindows.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnCraftWindows;
                    @InventoryWindows.started -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnInventoryWindows;
                    @InventoryWindows.performed -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnInventoryWindows;
                    @InventoryWindows.canceled -= m_Wrapper.m_PlayerMainActionsCallbackInterface.OnInventoryWindows;
                }
                m_Wrapper.m_PlayerMainActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Movement.started += instance.OnMovement;
                    @Movement.performed += instance.OnMovement;
                    @Movement.canceled += instance.OnMovement;
                    @Look.started += instance.OnLook;
                    @Look.performed += instance.OnLook;
                    @Look.canceled += instance.OnLook;
                    @FastUsing0.started += instance.OnFastUsing0;
                    @FastUsing0.performed += instance.OnFastUsing0;
                    @FastUsing0.canceled += instance.OnFastUsing0;
                    @FastUsing1.started += instance.OnFastUsing1;
                    @FastUsing1.performed += instance.OnFastUsing1;
                    @FastUsing1.canceled += instance.OnFastUsing1;
                    @FastUsing2.started += instance.OnFastUsing2;
                    @FastUsing2.performed += instance.OnFastUsing2;
                    @FastUsing2.canceled += instance.OnFastUsing2;
                    @FastUsing3.started += instance.OnFastUsing3;
                    @FastUsing3.performed += instance.OnFastUsing3;
                    @FastUsing3.canceled += instance.OnFastUsing3;
                    @FastUsing4.started += instance.OnFastUsing4;
                    @FastUsing4.performed += instance.OnFastUsing4;
                    @FastUsing4.canceled += instance.OnFastUsing4;
                    @FastUsing5.started += instance.OnFastUsing5;
                    @FastUsing5.performed += instance.OnFastUsing5;
                    @FastUsing5.canceled += instance.OnFastUsing5;
                    @FastUsing6.started += instance.OnFastUsing6;
                    @FastUsing6.performed += instance.OnFastUsing6;
                    @FastUsing6.canceled += instance.OnFastUsing6;
                    @FastUsing7.started += instance.OnFastUsing7;
                    @FastUsing7.performed += instance.OnFastUsing7;
                    @FastUsing7.canceled += instance.OnFastUsing7;
                    @FastUsing8.started += instance.OnFastUsing8;
                    @FastUsing8.performed += instance.OnFastUsing8;
                    @FastUsing8.canceled += instance.OnFastUsing8;
                    @FastUsing9.started += instance.OnFastUsing9;
                    @FastUsing9.performed += instance.OnFastUsing9;
                    @FastUsing9.canceled += instance.OnFastUsing9;
                    @CraftWindows.started += instance.OnCraftWindows;
                    @CraftWindows.performed += instance.OnCraftWindows;
                    @CraftWindows.canceled += instance.OnCraftWindows;
                    @InventoryWindows.started += instance.OnInventoryWindows;
                    @InventoryWindows.performed += instance.OnInventoryWindows;
                    @InventoryWindows.canceled += instance.OnInventoryWindows;
                }
            }
        }
        public PlayerMainActions @PlayerMain => new PlayerMainActions(this);

        // PlayerUse
        private readonly InputActionMap m_PlayerUse;
        private IPlayerUseActions m_PlayerUseActionsCallbackInterface;
        private readonly InputAction m_PlayerUse_Movement;
        private readonly InputAction m_PlayerUse_Look;
        public struct PlayerUseActions
        {
            private @PlayerInputActions m_Wrapper;
            public PlayerUseActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Movement => m_Wrapper.m_PlayerUse_Movement;
            public InputAction @Look => m_Wrapper.m_PlayerUse_Look;
            public InputActionMap Get() { return m_Wrapper.m_PlayerUse; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerUseActions set) { return set.Get(); }
            public void SetCallbacks(IPlayerUseActions instance)
            {
                if (m_Wrapper.m_PlayerUseActionsCallbackInterface != null)
                {
                    @Movement.started -= m_Wrapper.m_PlayerUseActionsCallbackInterface.OnMovement;
                    @Movement.performed -= m_Wrapper.m_PlayerUseActionsCallbackInterface.OnMovement;
                    @Movement.canceled -= m_Wrapper.m_PlayerUseActionsCallbackInterface.OnMovement;
                    @Look.started -= m_Wrapper.m_PlayerUseActionsCallbackInterface.OnLook;
                    @Look.performed -= m_Wrapper.m_PlayerUseActionsCallbackInterface.OnLook;
                    @Look.canceled -= m_Wrapper.m_PlayerUseActionsCallbackInterface.OnLook;
                }
                m_Wrapper.m_PlayerUseActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Movement.started += instance.OnMovement;
                    @Movement.performed += instance.OnMovement;
                    @Movement.canceled += instance.OnMovement;
                    @Look.started += instance.OnLook;
                    @Look.performed += instance.OnLook;
                    @Look.canceled += instance.OnLook;
                }
            }
        }
        public PlayerUseActions @PlayerUse => new PlayerUseActions(this);

        // Window
        private readonly InputActionMap m_Window;
        private IWindowActions m_WindowActionsCallbackInterface;
        private readonly InputAction m_Window_CloseWindows;
        public struct WindowActions
        {
            private @PlayerInputActions m_Wrapper;
            public WindowActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @CloseWindows => m_Wrapper.m_Window_CloseWindows;
            public InputActionMap Get() { return m_Wrapper.m_Window; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(WindowActions set) { return set.Get(); }
            public void SetCallbacks(IWindowActions instance)
            {
                if (m_Wrapper.m_WindowActionsCallbackInterface != null)
                {
                    @CloseWindows.started -= m_Wrapper.m_WindowActionsCallbackInterface.OnCloseWindows;
                    @CloseWindows.performed -= m_Wrapper.m_WindowActionsCallbackInterface.OnCloseWindows;
                    @CloseWindows.canceled -= m_Wrapper.m_WindowActionsCallbackInterface.OnCloseWindows;
                }
                m_Wrapper.m_WindowActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @CloseWindows.started += instance.OnCloseWindows;
                    @CloseWindows.performed += instance.OnCloseWindows;
                    @CloseWindows.canceled += instance.OnCloseWindows;
                }
            }
        }
        public WindowActions @Window => new WindowActions(this);
        public interface IPlayerMainActions
        {
            void OnMovement(InputAction.CallbackContext context);
            void OnLook(InputAction.CallbackContext context);
            void OnFastUsing0(InputAction.CallbackContext context);
            void OnFastUsing1(InputAction.CallbackContext context);
            void OnFastUsing2(InputAction.CallbackContext context);
            void OnFastUsing3(InputAction.CallbackContext context);
            void OnFastUsing4(InputAction.CallbackContext context);
            void OnFastUsing5(InputAction.CallbackContext context);
            void OnFastUsing6(InputAction.CallbackContext context);
            void OnFastUsing7(InputAction.CallbackContext context);
            void OnFastUsing8(InputAction.CallbackContext context);
            void OnFastUsing9(InputAction.CallbackContext context);
            void OnCraftWindows(InputAction.CallbackContext context);
            void OnInventoryWindows(InputAction.CallbackContext context);
        }
        public interface IPlayerUseActions
        {
            void OnMovement(InputAction.CallbackContext context);
            void OnLook(InputAction.CallbackContext context);
        }
        public interface IWindowActions
        {
            void OnCloseWindows(InputAction.CallbackContext context);
        }
    }
}
