//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Players
{
    public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""PlayerMove"",
            ""id"": ""d2239dd4-b303-40d6-9433-310177f0543a"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""5dae9d0c-371f-4b6c-b969-02f5a0aac98a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""9b0ee411-d3d6-4eac-b43f-ba381a4ebeb6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c23c5754-4c95-47da-b544-f0b49593e1e8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""37f01c9c-3f93-4171-9b82-1841c32bf2ee"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3adae854-72b1-4394-afd1-49ca9f237da2"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a52b4251-b820-4206-a8c8-27bf703d6f24"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8dd328fc-2d7f-45be-97b4-43c9a6f25e64"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d37c9387-aef5-4183-83dc-06727ba2c46c"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Windows"",
            ""id"": ""24943bc7-01f4-4045-a4ae-f9f678ea2aaa"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""eb50607a-c5aa-40db-8098-6504aae33c03"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CloseWindows"",
                    ""type"": ""Button"",
                    ""id"": ""b9592ede-49fc-473a-b383-f1423995ca4c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CraftWindows"",
                    ""type"": ""Button"",
                    ""id"": ""77b7fa1f-4617-425a-87cb-6561effc471e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryWindows"",
                    ""type"": ""Button"",
                    ""id"": ""8a736115-024a-4df9-919a-0c1370f7878f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c31dbb1a-4e90-4a31-83a6-b530019b30f4"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b001da54-2561-4e85-983b-91e2d6151ff5"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseWindows"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5b6d96d-0e56-4233-ae86-258a5e0b0b8e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CraftWindows"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""acb90a27-a1b3-462a-981e-5753b73f753a"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryWindows"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UsingBefore"",
            ""id"": ""4e0913e4-3d50-4a10-93be-b38986aa2445"",
            ""actions"": [
                {
                    ""name"": ""FastUsing0"",
                    ""type"": ""Button"",
                    ""id"": ""4ce39e19-78bc-4697-9f31-d02b1cc84127"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastUsing1"",
                    ""type"": ""Button"",
                    ""id"": ""c97790da-ef3f-4d7b-bb8e-5137b9acc87f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastUsing2"",
                    ""type"": ""Button"",
                    ""id"": ""2c7941e4-9fe2-4b41-a595-7ac51300a5ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastUsing3"",
                    ""type"": ""Button"",
                    ""id"": ""856d84eb-cc82-459b-a460-9bd49383fce0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastUsing4"",
                    ""type"": ""Button"",
                    ""id"": ""db3e61f3-5cd1-4d20-a1a4-3a143f0b17ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastUsing5"",
                    ""type"": ""Button"",
                    ""id"": ""75655ae2-8759-457e-8455-2f15568333ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastUsing6"",
                    ""type"": ""Button"",
                    ""id"": ""f8f1d7ff-8b6d-4b6b-be0e-3d90d3ea5a76"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastUsing7"",
                    ""type"": ""Button"",
                    ""id"": ""d60eed6a-ed8f-4c8e-b4da-5ea65e642547"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastUsing8"",
                    ""type"": ""Button"",
                    ""id"": ""397c6580-8061-4f27-ae26-14c2c2c16780"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastUsing9"",
                    ""type"": ""Button"",
                    ""id"": ""38216683-cd9d-4eff-8fcb-2c18722ad1cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a91fda36-4d80-49ed-98e9-27e20fcc32f4"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastUsing0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95e20aaa-754c-4476-a88e-b43117925477"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastUsing1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5124e09f-457f-44aa-9ed8-dfeec0e286ce"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastUsing2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35501626-f08c-4a95-9e34-11980f36f760"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastUsing3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0488e0fa-8608-42c2-83ff-856c936247e9"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastUsing4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d185cf2-d5ad-4796-aab0-56f563da2415"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastUsing5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""347d28e2-63c4-4cb8-bfb0-9c8788a57f19"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastUsing6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c945cbeb-679d-4faf-b5a0-dec841cf9c04"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastUsing7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0692aef2-bcc1-4688-b581-ee5c307f2653"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastUsing8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4f5c726-c1c9-4ce1-b895-bed79c548d3f"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastUsing9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UsingAfter"",
            ""id"": ""662a335a-ef3d-44e4-ae74-14015d1ade9a"",
            ""actions"": [
                {
                    ""name"": ""UsingSubmit"",
                    ""type"": ""Button"",
                    ""id"": ""f642b445-8954-4f5b-a821-899acf6d6067"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UsingCancel"",
                    ""type"": ""Button"",
                    ""id"": ""45e055fb-b629-4a8e-a789-ffa26846774f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""be951f12-c0ba-499b-9195-65373082d5bc"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UsingSubmit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d86eace1-c925-459a-88e9-113ed92d1b28"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UsingSubmit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46927bb5-28d0-4cb0-9a7c-c2a568b07361"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UsingCancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // PlayerMove
            m_PlayerMove = asset.FindActionMap("PlayerMove", throwIfNotFound: true);
            m_PlayerMove_Movement = m_PlayerMove.FindAction("Movement", throwIfNotFound: true);
            m_PlayerMove_Look = m_PlayerMove.FindAction("Look", throwIfNotFound: true);
            // Windows
            m_Windows = asset.FindActionMap("Windows", throwIfNotFound: true);
            m_Windows_Newaction = m_Windows.FindAction("New action", throwIfNotFound: true);
            m_Windows_CloseWindows = m_Windows.FindAction("CloseWindows", throwIfNotFound: true);
            m_Windows_CraftWindows = m_Windows.FindAction("CraftWindows", throwIfNotFound: true);
            m_Windows_InventoryWindows = m_Windows.FindAction("InventoryWindows", throwIfNotFound: true);
            // UsingBefore
            m_UsingBefore = asset.FindActionMap("UsingBefore", throwIfNotFound: true);
            m_UsingBefore_FastUsing0 = m_UsingBefore.FindAction("FastUsing0", throwIfNotFound: true);
            m_UsingBefore_FastUsing1 = m_UsingBefore.FindAction("FastUsing1", throwIfNotFound: true);
            m_UsingBefore_FastUsing2 = m_UsingBefore.FindAction("FastUsing2", throwIfNotFound: true);
            m_UsingBefore_FastUsing3 = m_UsingBefore.FindAction("FastUsing3", throwIfNotFound: true);
            m_UsingBefore_FastUsing4 = m_UsingBefore.FindAction("FastUsing4", throwIfNotFound: true);
            m_UsingBefore_FastUsing5 = m_UsingBefore.FindAction("FastUsing5", throwIfNotFound: true);
            m_UsingBefore_FastUsing6 = m_UsingBefore.FindAction("FastUsing6", throwIfNotFound: true);
            m_UsingBefore_FastUsing7 = m_UsingBefore.FindAction("FastUsing7", throwIfNotFound: true);
            m_UsingBefore_FastUsing8 = m_UsingBefore.FindAction("FastUsing8", throwIfNotFound: true);
            m_UsingBefore_FastUsing9 = m_UsingBefore.FindAction("FastUsing9", throwIfNotFound: true);
            // UsingAfter
            m_UsingAfter = asset.FindActionMap("UsingAfter", throwIfNotFound: true);
            m_UsingAfter_UsingSubmit = m_UsingAfter.FindAction("UsingSubmit", throwIfNotFound: true);
            m_UsingAfter_UsingCancel = m_UsingAfter.FindAction("UsingCancel", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // PlayerMove
        private readonly InputActionMap m_PlayerMove;
        private IPlayerMoveActions m_PlayerMoveActionsCallbackInterface;
        private readonly InputAction m_PlayerMove_Movement;
        private readonly InputAction m_PlayerMove_Look;
        public struct PlayerMoveActions
        {
            private @PlayerInputActions m_Wrapper;
            public PlayerMoveActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Movement => m_Wrapper.m_PlayerMove_Movement;
            public InputAction @Look => m_Wrapper.m_PlayerMove_Look;
            public InputActionMap Get() { return m_Wrapper.m_PlayerMove; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerMoveActions set) { return set.Get(); }
            public void SetCallbacks(IPlayerMoveActions instance)
            {
                if (m_Wrapper.m_PlayerMoveActionsCallbackInterface != null)
                {
                    @Movement.started -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnMovement;
                    @Movement.performed -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnMovement;
                    @Movement.canceled -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnMovement;
                    @Look.started -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnLook;
                    @Look.performed -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnLook;
                    @Look.canceled -= m_Wrapper.m_PlayerMoveActionsCallbackInterface.OnLook;
                }
                m_Wrapper.m_PlayerMoveActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Movement.started += instance.OnMovement;
                    @Movement.performed += instance.OnMovement;
                    @Movement.canceled += instance.OnMovement;
                    @Look.started += instance.OnLook;
                    @Look.performed += instance.OnLook;
                    @Look.canceled += instance.OnLook;
                }
            }
        }
        public PlayerMoveActions @PlayerMove => new PlayerMoveActions(this);

        // Windows
        private readonly InputActionMap m_Windows;
        private IWindowsActions m_WindowsActionsCallbackInterface;
        private readonly InputAction m_Windows_Newaction;
        private readonly InputAction m_Windows_CloseWindows;
        private readonly InputAction m_Windows_CraftWindows;
        private readonly InputAction m_Windows_InventoryWindows;
        public struct WindowsActions
        {
            private @PlayerInputActions m_Wrapper;
            public WindowsActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Newaction => m_Wrapper.m_Windows_Newaction;
            public InputAction @CloseWindows => m_Wrapper.m_Windows_CloseWindows;
            public InputAction @CraftWindows => m_Wrapper.m_Windows_CraftWindows;
            public InputAction @InventoryWindows => m_Wrapper.m_Windows_InventoryWindows;
            public InputActionMap Get() { return m_Wrapper.m_Windows; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(WindowsActions set) { return set.Get(); }
            public void SetCallbacks(IWindowsActions instance)
            {
                if (m_Wrapper.m_WindowsActionsCallbackInterface != null)
                {
                    @Newaction.started -= m_Wrapper.m_WindowsActionsCallbackInterface.OnNewaction;
                    @Newaction.performed -= m_Wrapper.m_WindowsActionsCallbackInterface.OnNewaction;
                    @Newaction.canceled -= m_Wrapper.m_WindowsActionsCallbackInterface.OnNewaction;
                    @CloseWindows.started -= m_Wrapper.m_WindowsActionsCallbackInterface.OnCloseWindows;
                    @CloseWindows.performed -= m_Wrapper.m_WindowsActionsCallbackInterface.OnCloseWindows;
                    @CloseWindows.canceled -= m_Wrapper.m_WindowsActionsCallbackInterface.OnCloseWindows;
                    @CraftWindows.started -= m_Wrapper.m_WindowsActionsCallbackInterface.OnCraftWindows;
                    @CraftWindows.performed -= m_Wrapper.m_WindowsActionsCallbackInterface.OnCraftWindows;
                    @CraftWindows.canceled -= m_Wrapper.m_WindowsActionsCallbackInterface.OnCraftWindows;
                    @InventoryWindows.started -= m_Wrapper.m_WindowsActionsCallbackInterface.OnInventoryWindows;
                    @InventoryWindows.performed -= m_Wrapper.m_WindowsActionsCallbackInterface.OnInventoryWindows;
                    @InventoryWindows.canceled -= m_Wrapper.m_WindowsActionsCallbackInterface.OnInventoryWindows;
                }
                m_Wrapper.m_WindowsActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Newaction.started += instance.OnNewaction;
                    @Newaction.performed += instance.OnNewaction;
                    @Newaction.canceled += instance.OnNewaction;
                    @CloseWindows.started += instance.OnCloseWindows;
                    @CloseWindows.performed += instance.OnCloseWindows;
                    @CloseWindows.canceled += instance.OnCloseWindows;
                    @CraftWindows.started += instance.OnCraftWindows;
                    @CraftWindows.performed += instance.OnCraftWindows;
                    @CraftWindows.canceled += instance.OnCraftWindows;
                    @InventoryWindows.started += instance.OnInventoryWindows;
                    @InventoryWindows.performed += instance.OnInventoryWindows;
                    @InventoryWindows.canceled += instance.OnInventoryWindows;
                }
            }
        }
        public WindowsActions @Windows => new WindowsActions(this);

        // UsingBefore
        private readonly InputActionMap m_UsingBefore;
        private IUsingBeforeActions m_UsingBeforeActionsCallbackInterface;
        private readonly InputAction m_UsingBefore_FastUsing0;
        private readonly InputAction m_UsingBefore_FastUsing1;
        private readonly InputAction m_UsingBefore_FastUsing2;
        private readonly InputAction m_UsingBefore_FastUsing3;
        private readonly InputAction m_UsingBefore_FastUsing4;
        private readonly InputAction m_UsingBefore_FastUsing5;
        private readonly InputAction m_UsingBefore_FastUsing6;
        private readonly InputAction m_UsingBefore_FastUsing7;
        private readonly InputAction m_UsingBefore_FastUsing8;
        private readonly InputAction m_UsingBefore_FastUsing9;
        public struct UsingBeforeActions
        {
            private @PlayerInputActions m_Wrapper;
            public UsingBeforeActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @FastUsing0 => m_Wrapper.m_UsingBefore_FastUsing0;
            public InputAction @FastUsing1 => m_Wrapper.m_UsingBefore_FastUsing1;
            public InputAction @FastUsing2 => m_Wrapper.m_UsingBefore_FastUsing2;
            public InputAction @FastUsing3 => m_Wrapper.m_UsingBefore_FastUsing3;
            public InputAction @FastUsing4 => m_Wrapper.m_UsingBefore_FastUsing4;
            public InputAction @FastUsing5 => m_Wrapper.m_UsingBefore_FastUsing5;
            public InputAction @FastUsing6 => m_Wrapper.m_UsingBefore_FastUsing6;
            public InputAction @FastUsing7 => m_Wrapper.m_UsingBefore_FastUsing7;
            public InputAction @FastUsing8 => m_Wrapper.m_UsingBefore_FastUsing8;
            public InputAction @FastUsing9 => m_Wrapper.m_UsingBefore_FastUsing9;
            public InputActionMap Get() { return m_Wrapper.m_UsingBefore; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(UsingBeforeActions set) { return set.Get(); }
            public void SetCallbacks(IUsingBeforeActions instance)
            {
                if (m_Wrapper.m_UsingBeforeActionsCallbackInterface != null)
                {
                    @FastUsing0.started -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing0;
                    @FastUsing0.performed -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing0;
                    @FastUsing0.canceled -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing0;
                    @FastUsing1.started -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing1;
                    @FastUsing1.performed -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing1;
                    @FastUsing1.canceled -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing1;
                    @FastUsing2.started -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing2;
                    @FastUsing2.performed -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing2;
                    @FastUsing2.canceled -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing2;
                    @FastUsing3.started -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing3;
                    @FastUsing3.performed -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing3;
                    @FastUsing3.canceled -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing3;
                    @FastUsing4.started -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing4;
                    @FastUsing4.performed -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing4;
                    @FastUsing4.canceled -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing4;
                    @FastUsing5.started -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing5;
                    @FastUsing5.performed -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing5;
                    @FastUsing5.canceled -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing5;
                    @FastUsing6.started -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing6;
                    @FastUsing6.performed -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing6;
                    @FastUsing6.canceled -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing6;
                    @FastUsing7.started -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing7;
                    @FastUsing7.performed -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing7;
                    @FastUsing7.canceled -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing7;
                    @FastUsing8.started -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing8;
                    @FastUsing8.performed -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing8;
                    @FastUsing8.canceled -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing8;
                    @FastUsing9.started -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing9;
                    @FastUsing9.performed -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing9;
                    @FastUsing9.canceled -= m_Wrapper.m_UsingBeforeActionsCallbackInterface.OnFastUsing9;
                }
                m_Wrapper.m_UsingBeforeActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @FastUsing0.started += instance.OnFastUsing0;
                    @FastUsing0.performed += instance.OnFastUsing0;
                    @FastUsing0.canceled += instance.OnFastUsing0;
                    @FastUsing1.started += instance.OnFastUsing1;
                    @FastUsing1.performed += instance.OnFastUsing1;
                    @FastUsing1.canceled += instance.OnFastUsing1;
                    @FastUsing2.started += instance.OnFastUsing2;
                    @FastUsing2.performed += instance.OnFastUsing2;
                    @FastUsing2.canceled += instance.OnFastUsing2;
                    @FastUsing3.started += instance.OnFastUsing3;
                    @FastUsing3.performed += instance.OnFastUsing3;
                    @FastUsing3.canceled += instance.OnFastUsing3;
                    @FastUsing4.started += instance.OnFastUsing4;
                    @FastUsing4.performed += instance.OnFastUsing4;
                    @FastUsing4.canceled += instance.OnFastUsing4;
                    @FastUsing5.started += instance.OnFastUsing5;
                    @FastUsing5.performed += instance.OnFastUsing5;
                    @FastUsing5.canceled += instance.OnFastUsing5;
                    @FastUsing6.started += instance.OnFastUsing6;
                    @FastUsing6.performed += instance.OnFastUsing6;
                    @FastUsing6.canceled += instance.OnFastUsing6;
                    @FastUsing7.started += instance.OnFastUsing7;
                    @FastUsing7.performed += instance.OnFastUsing7;
                    @FastUsing7.canceled += instance.OnFastUsing7;
                    @FastUsing8.started += instance.OnFastUsing8;
                    @FastUsing8.performed += instance.OnFastUsing8;
                    @FastUsing8.canceled += instance.OnFastUsing8;
                    @FastUsing9.started += instance.OnFastUsing9;
                    @FastUsing9.performed += instance.OnFastUsing9;
                    @FastUsing9.canceled += instance.OnFastUsing9;
                }
            }
        }
        public UsingBeforeActions @UsingBefore => new UsingBeforeActions(this);

        // UsingAfter
        private readonly InputActionMap m_UsingAfter;
        private IUsingAfterActions m_UsingAfterActionsCallbackInterface;
        private readonly InputAction m_UsingAfter_UsingSubmit;
        private readonly InputAction m_UsingAfter_UsingCancel;
        public struct UsingAfterActions
        {
            private @PlayerInputActions m_Wrapper;
            public UsingAfterActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @UsingSubmit => m_Wrapper.m_UsingAfter_UsingSubmit;
            public InputAction @UsingCancel => m_Wrapper.m_UsingAfter_UsingCancel;
            public InputActionMap Get() { return m_Wrapper.m_UsingAfter; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(UsingAfterActions set) { return set.Get(); }
            public void SetCallbacks(IUsingAfterActions instance)
            {
                if (m_Wrapper.m_UsingAfterActionsCallbackInterface != null)
                {
                    @UsingSubmit.started -= m_Wrapper.m_UsingAfterActionsCallbackInterface.OnUsingSubmit;
                    @UsingSubmit.performed -= m_Wrapper.m_UsingAfterActionsCallbackInterface.OnUsingSubmit;
                    @UsingSubmit.canceled -= m_Wrapper.m_UsingAfterActionsCallbackInterface.OnUsingSubmit;
                    @UsingCancel.started -= m_Wrapper.m_UsingAfterActionsCallbackInterface.OnUsingCancel;
                    @UsingCancel.performed -= m_Wrapper.m_UsingAfterActionsCallbackInterface.OnUsingCancel;
                    @UsingCancel.canceled -= m_Wrapper.m_UsingAfterActionsCallbackInterface.OnUsingCancel;
                }
                m_Wrapper.m_UsingAfterActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @UsingSubmit.started += instance.OnUsingSubmit;
                    @UsingSubmit.performed += instance.OnUsingSubmit;
                    @UsingSubmit.canceled += instance.OnUsingSubmit;
                    @UsingCancel.started += instance.OnUsingCancel;
                    @UsingCancel.performed += instance.OnUsingCancel;
                    @UsingCancel.canceled += instance.OnUsingCancel;
                }
            }
        }
        public UsingAfterActions @UsingAfter => new UsingAfterActions(this);
        public interface IPlayerMoveActions
        {
            void OnMovement(InputAction.CallbackContext context);
            void OnLook(InputAction.CallbackContext context);
        }
        public interface IWindowsActions
        {
            void OnNewaction(InputAction.CallbackContext context);
            void OnCloseWindows(InputAction.CallbackContext context);
            void OnCraftWindows(InputAction.CallbackContext context);
            void OnInventoryWindows(InputAction.CallbackContext context);
        }
        public interface IUsingBeforeActions
        {
            void OnFastUsing0(InputAction.CallbackContext context);
            void OnFastUsing1(InputAction.CallbackContext context);
            void OnFastUsing2(InputAction.CallbackContext context);
            void OnFastUsing3(InputAction.CallbackContext context);
            void OnFastUsing4(InputAction.CallbackContext context);
            void OnFastUsing5(InputAction.CallbackContext context);
            void OnFastUsing6(InputAction.CallbackContext context);
            void OnFastUsing7(InputAction.CallbackContext context);
            void OnFastUsing8(InputAction.CallbackContext context);
            void OnFastUsing9(InputAction.CallbackContext context);
        }
        public interface IUsingAfterActions
        {
            void OnUsingSubmit(InputAction.CallbackContext context);
            void OnUsingCancel(InputAction.CallbackContext context);
        }
    }
}
